name: Frontend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.14.0]

    steps:
    - uses: actions/checkout@v4
    
    # Setup Node.js environment with proper cache directory
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json # Ensure it caches from the correct directory

    # Install dependencies inside frontend/
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm ci

    # Build frontend
    - name: Build frontend
      working-directory: ./frontend
      run: npm run build --if-present  || echo "Ignoring build errors"

    # Run frontend tests
    - name: Run frontend tests
      working-directory: ./frontend
      run: npm test

    # Deploy frontend with gh-pages
    - name: Deploy frontend with gh-pages
      working-directory: ./frontend
      run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
